### ISSUE TITLE
Test Issue - no labels

### ISSUE THREAD

**Issue by mellieA** [zuchka/grafana-action-test#24]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by zuchka** [comment]
@mellieA  please add an appropriate label. This helps the teams triage issues as fast as possible. Please keep the `internal` tag so we can track issues created by grafanistas. Thank you!
